---
title: "Day2Presentation"
output: html_document
date: "2025-01-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Initial Problem: 
**Does a higher GDP correlate with greater issuance of F1 and H1B visas?**

# Follow-ups
Additionally, we can explore potential secondary questions, such as:

- **How do presidential terms relate to the number of visa issuances?**

- **What policies drive fluctuations in F1 and H1B visa approvals?**

# Background  

- **What is H1B work visa?**  

  The H-1B program applies to employers seeking to hire nonimmigrant aliens as workers in specialty occupations or as fashion models of distinguished merit and ability. A specialty occupation is one that requires the application of a body of highly specialized knowledge and the attainment of at least a bachelor’s degree or its equivalent. (Dol.gov)  

- **H1B Policies change over time**  

  - 1998 Industry Lobbying: High-tech industry representatives lobbied for an increase in the H-1B visa cap.  

  - In September 1997, the 65,000 annual cap for H-1B visas was reached for the first time. The cap provided new evidence of unmet demand for high-tech workers, particularly in the computer industry.  

  - In 1998, bills were introduced in the House and Senate to raise the H-1B cap from 65,000 to 115,000.  

  - Cap was lifted to 195,000 visas for 2001, 2002, and 2003 under the 2000 American Competitiveness in the 21st Century Act (AC-21).  

  - The annual H-1B cap reverted to 65,000 in 2004.  

  - To protect American workers during the recession, Congress targeted the H-1B program in the American Recovery and Reinvestment Act of 2009.  

  - The number of filed petitions fell by nearly 20 percent between 2007 and 2009.  

  - H-1B fees also fluctuate.  

- **What is F1 student Visa**

  -The F-1 visa allows a student to temporarily live in the United States for a defined period of time while studying at a school, college, seminary, or conservatory. 
  
- **Policies on F1**

  -Eyad Ismoil, one of the World Trade Center bombing terrorists, is in the United States on an expired student visa.
  
  -The Illegal Immigration Reform and Immigrant Responsibility Act of 1996 (IIRIRA) directs the Attorney General to conduct a program to collect certain information on nonimmigrant foreign students and exchange visitors from approved institutions
  
  -In 2002, An interim final rule is announced, requiring anybody on a B visa to transition to a F or M visa prior to starting a program of study.
  
  
Works Cited

- https://www.dol.gov/agencies/whd/immigration/h1b

- https://ccis.ucsd.edu/_files/wp11.pdf

- https://www.migrationpolicy.org/article/h-1b-temporary-skilled-worker-program

- https://timelines.issarice.com/wiki/Timeline_of_student_visa_policy_in_the_United_States
